### ISSUE TITLE
Vehicles get damaged

### ISSUE THREAD

**Issue by KarliCarlos** [Kiminaze/VehicleDeformation#2]
Vehicles randomly get smushed 
![image](https://user-images.githubusercontent.com/88288166/150647248-d468e846-882a-42aa-bb55-544097955fc8.png)

**Comment by lexinor** [comment]
Still no fixes found ?

**Comment by KarliCarlos** [comment]
I had VehicleDeformation and AdvancedParking activated. Just forgot to close the issue 😅

**Comment by lexinor** [comment]
To fix the problem with AdvancedParking you use this code instead ?

**Comment by KarliCarlos** [comment]
> To fix the problem with AdvancedParking you use this code instead ?

No the other way around

**Comment by Kiminaze** [comment]
Sorry, completely must have missed this issue ^^'

Apart from having AdvancedParking and VehicleDeformation running at the same time:
This is a common issue especially with modded vehicles. I could get into details, but that would take too long to write here :D

Also keep in mind that the "example" is meant as just that. It works for the most part, but is not really meant for production servers. It just shows how you could sync it between players.

AdvancedParking also uses basically the same code as this resources example. So there is no magical "fixing" the problem with that.
