### ISSUE TITLE
damage bodywork parts

### ISSUE THREAD

**Issue by Mesrine67** [Kiminaze/VehicleDeformation#5]
Do you have any ideas on how to add grooming synchro to missing doors or even the bonnet of the vehicle?

[preview](https://streamable.com/h63b1z)

**Comment by iSentrie** [comment]
It's up to your extras script, save damage and return once extra is changed.

**Comment by Kiminaze** [comment]
Check this native: https://docs.fivem.net/natives/?_0x5F3A3574
